export const SIGNUP_FIELDS = [
  {
    type: 'text',
    name: 'first_name',
    label: 'First name',
    placeholder: 'Enter your first name',
    required: true,
  },
  {
    type: 'text',
    name: 'middle_name',
    label: 'Middle name',
    placeholder: 'Enter your middle name',
    required: false,
  },
  {
    type: 'text',
    name: 'last_name',
    label: 'Last name',
    placeholder: 'Enter your last name',
    required: true,
  },
  {
    type: 'date',
    name: 'dob',
    label: 'Date of Birth',
    required: true,
  },
  {
    type: 'text',
    name: 'phone',
    label: 'Phone',
    placeholder: 'Enter your phone number',
    required: true,
  },
  {
    type: 'email',
    name: 'email',
    label: 'Email',
    placeholder: 'Enter your email',
    required: true,
  },
  {
    type: 'password',
    name: 'password',
    label: 'Password',
    placeholder: 'Enter your password',
    required: true,
  },
];